#!/bin/bash
# /test-patient-subscriptions.sh

echo "Patient Subscription Testing Guide"
echo "================================="
echo ""
echo "1. Start your Meteor application:"
echo "   meteor run --settings configs/settings.synthea.json"
echo ""
echo "2. Open your browser console (F12) and navigate to the Patient Directory"
echo ""
echo "3. Click on a patient to select them"
echo ""
echo "4. In the console, you should see:"
echo "   - 'Activating patient subscriptions...'"
echo "   - Multiple 'Subscribing to autopublish.*' messages"
echo "   - 'Active subscriptions:' with a list of resources"
echo "   - Each resource showing 'ready: true' when loaded"
echo ""
echo "5. Navigate to the Patient Chart (/patient-chart)"
echo ""
echo "6. Verify that patient data is displayed for:"
echo "   - Conditions"
echo "   - Procedures"
echo "   - Observations"
echo "   - Medications"
echo "   - etc."
echo ""
echo "7. To verify in the browser console:"
echo "   import patientSubscriptionManager from '/imports/client/subscriptions/PatientSubscriptionManager';"
echo "   patientSubscriptionManager.getActiveSubscriptions();"
echo "   patientSubscriptionManager.isReady();"
echo ""
echo "8. Check specific collections:"
echo "   Conditions.find().count();"
echo "   Procedures.find().count();"
echo "   Observations.find().count();"
echo ""