// certification/scroll-heights.js
// Pass-1 -> pass-2 bridge for the scroll edition of the Software Manual.
//
// Reads the .aux produced by pass 1 of care-commons-ehr-software-manual-scroll.tex
// (uniform 199in pages), joins each \scrollmarkpage{id}{page} record with its
// \zref@newlabel{scrollend-id}{...\posy{sp}...} position, and emits
// scroll-heights.tex assigning each page the height of its content plus a 1in
// bottom margin. Run via build-scroll-edition.sh.
//
// Usage: node scroll-heights.js <aux-file>

const fs = require('fs');
const get = (obj, key, dflt) => (obj && obj[key] !== undefined ? obj[key] : dflt);

const SP_PER_PT = 65536;
const PT_PER_IN = 72.27;               // TeX points per inch
const SP_PER_IN = SP_PER_PT * PT_PER_IN;
const PASS1_HEIGHT_SP = Math.round(199 * SP_PER_IN);   // must match the shell's paperheight
const BOTTOM_MARGIN_SP = Math.round(1 * SP_PER_IN);
const MIN_HEIGHT_SP = Math.round(4 * SP_PER_IN);       // floor for tiny scrolls
const MAX_HEIGHT_SP = PASS1_HEIGHT_SP;

const auxPath = process.argv[2];
if (!auxPath) {
  console.error('[scroll-heights] usage: node scroll-heights.js <aux-file>');
  process.exit(1);
}
const aux = fs.readFileSync(auxPath, 'utf8');

// \scrollmarkpage{id}{page}
const markToPage = {};
for (const m of aux.matchAll(/\\scrollmarkpage\{(\d+)\}\{(\d+)\}/g)) {
  markToPage[m[1]] = parseInt(m[2], 10);
}

// \zref@newlabel{scrollend-id}{\posx{..}\posy{..}}
const markToPosy = {};
for (const m of aux.matchAll(/\\zref@newlabel\{scrollend-(\d+)\}\{(.*)\}/g)) {
  const posy = m[2].match(/\\posy\{(\d+)\}/);
  if (posy) markToPosy[m[1]] = parseInt(posy[1], 10);
}

// Lowest ink point per page (posy measured from the page bottom, so min wins)
const pageMinPosy = {};
for (const [id, page] of Object.entries(markToPage)) {
  const posy = get(markToPosy, id, undefined);
  if (posy === undefined) {
    console.error(`[scroll-heights] mark ${id} (page ${page}) has no position; skipping`);
    continue;
  }
  if (pageMinPosy[page] === undefined || posy < pageMinPosy[page]) {
    pageMinPosy[page] = posy;
  }
}

const pages = Object.keys(pageMinPosy).map(Number).sort((a, b) => a - b);
if (pages.length === 0) {
  console.error('[scroll-heights] no marks found in aux; refusing to emit an empty heights file');
  process.exit(1);
}

const lines = [
  '% scroll-heights.tex --- GENERATED by scroll-heights.js (pass 1 measurements).',
  '% Do not edit or commit; rebuilt by build-scroll-edition.sh.',
];
for (const page of pages) {
  const contentDepth = PASS1_HEIGHT_SP - pageMinPosy[page];
  let height = contentDepth + BOTTOM_MARGIN_SP;
  height = Math.max(MIN_HEIGHT_SP, Math.min(MAX_HEIGHT_SP, height));
  lines.push(`\\expandafter\\gdef\\csname scrollh@${page}\\endcsname{${height}sp}`);
  console.error(`[scroll-heights] page ${page}: ${(height / SP_PER_IN).toFixed(1)}in`);
}
process.stdout.write(lines.join('\n') + '\n');
