import React, { createContext, useContext, useState, useLayoutEffect, useEffect, useMemo } from 'react';
import { Hello } from './Hello.jsx';

import { get, set } from 'lodash';

import { Session } from 'meteor/session';
import { Meteor } from 'meteor/meteor';

import { Helmet } from "react-helmet";

import {
  createBrowserRouter,
  RouterProvider,
  useNavigate,
  BrowserRouter as Router, 
  Routes, 
  Route,
  Outlet
} from "react-router-dom";

import { useTracker } from 'meteor/react-meteor-data';
import { Container, Box, CircularProgress } from '@mui/material';

// import NotFound from './NotFound.jsx';
// import AppCanvas from './AppCanvas.jsx';
import Header from './Header.jsx';
import Footer from './Footer.jsx';
import SideDrawer from './SideDrawer';
// import SettingsPage from './SettingsPage';
// import ContextSlideOut from './ContextSlideOut';


import GettingStartedPage from './GettingStartedPage.jsx';
import MeteorBasic from './MeteorBasic.jsx';
import StaticPatientFileLoaderPage from './StaticPatientFileLoaderPage.jsx';

import SmartLauncher from './SmartLauncher.jsx';
import SmartLaunchDebugger from './SmartLaunchDebugger.jsx';
import SmartAppDebugger from './SmartAppDebugger.jsx';
import SmartSampleApp from './SmartSampleApp.jsx';
import BackendAuthPage from './BackendAuthPage.jsx';
import ThemingPage from './ThemingPage.jsx';

import CdsHooksDebugger from './CdsHooksDebugger.jsx';

import NoDataWrapper from './NoDataWrapper.jsx';
import NotSignedInWrapper from './NotSignedInWrapper.jsx';
import NoPatientSelectedCard from './components/NoPatientSelectedCard.jsx';
import AuthenticatedRoute from './components/AuthenticatedRoute.jsx';
import WelcomeDialog from './components/WelcomeDialog.jsx';

import HomePage from './HomePage.jsx';
import ServerConfigurationPage from '../ui-vault-server/ServerConfigurationPage.jsx';
import UdapRegistrationPage from '../ui-vault-server/UdapRegistrationPage.jsx';
import OAuthClientsPage from '../ui-vault-server/OAuthClientsPage.jsx';
import OAuthPatientPickerPage from './OAuthPatientPickerPage.jsx';
import FhirBasePage from './pages/FhirBasePage.jsx';
import NotFoundPage from './pages/NotFoundPage.jsx';
import SwaggerPage from '../ui-vault-server/SwaggerPage.jsx';

// Business page components
import { 
  AboutPage, 
  EulaPage, 
  PrivacyPage, 
  SupportPage, 
  TermsPage 
} from './pages/index.business.js';

// Account components (conditionally loaded)
import { LoginPage } from '../accounts/client/pages/LoginPage';
import { RegisterPage } from '../accounts/client/pages/RegisterPage';
import { ForgotPasswordPage } from '../accounts/client/pages/ForgotPasswordPage';
import { VerifyEmailPage } from '../accounts/client/pages/VerifyEmailPage';
import { ResetPasswordPage } from '../accounts/client/pages/ResetPasswordPage';
import { EnrollAccountPage } from '../accounts/client/pages/EnrollAccountPage';
import { TwoFactorSetupPage } from '../accounts/client/pages/TwoFactorSetupPage';

import PatientQuickChart from '../patient/PatientQuickChart.jsx';
import PatientChart from '../patient/PatientChart.jsx';
import EnhancedCarePlanDesigner from '../ui-fhir/carePlans/EnhancedCarePlanDesigner.jsx';


//===============================================================================================================
// Modules

import PatientsDirectory from '../ui-modules/PatientsDirectory.jsx';
import BiomarkerChartingPage from '../ui-modules/BiomarkerChartingPage.jsx';

// DICOM Viewer
import StudyListPage from './DICOM/StudyListPage.jsx';
import UploadPage from './DICOM/UploadPage.jsx';
import DicomViewerPage from './DICOM/DicomViewerPage.jsx';

// External Content / iFrame
import ExternalContentPage from './ExternalContentPage.jsx';
import ExternalContentPanel from './ExternalContentPanel.jsx';

// Optional package imports would go here when packages are added

//===============================================================================================================
// WorkflowRegistry - Build-time workflow loading via Rspack plugin
// Barrel files are auto-generated by configs/rspack.workflowParser.js from configs/workflows.json
// See configs/workflows.json to enable/disable workflows, or use EXTRA_WORKFLOWS env var

import WorkflowRegistry from '/imports/lib/WorkflowRegistry.js';

// Import the generated loader - this is a static import that rspack can bundle
// The barrel file is generated at build time by rspack.workflowParser.js
import { registerWorkflows } from '@workflows/loader.js';

// Register all workflows at module initialization (before React renders)
registerWorkflows();

// Hook to reactively get workflow routes
// This allows components to re-render when workflows are registered
function useWorkflowRoutes() {
  const [workflowRoutes, setWorkflowRoutes] = useState(WorkflowRegistry.getRoutes());

  useEffect(() => {
    // Subscribe to WorkflowRegistry changes to update state when workflows register
    const unsubscribe = WorkflowRegistry.subscribe(() => {
      setWorkflowRoutes([...WorkflowRegistry.getRoutes()]);
    });

    return unsubscribe;
  }, []);

  return { workflowRoutes, isLoading: false };
}

//===============================================================================================================
// FHIR Page Components

import {
  ActivityDefinitionsPage,
  AllergyIntolerancesPage,
  ArtifactAssessmentsPage,
  BasicsPage,
  BundlesPage,
  CarePlanDesignerPage,
  CarePlanDetailPage,
  CareTeamsPage,
  CarePlansPage,
  ClaimsPage,
  CodeSystemsPage,
  CompositionsPage,
  ConditionsPage,
  ConsentsPage,
  DevicesPage,
  DocumentReferencesPage,
  EncountersPage,
  EvidencesPage,
  GoalsPage,
  GuidanceResponsesPage,
  ImmunizationsPage,
  LibrariesPage,
  LocationsPage,
  MedicationsPage,
  MedicationRequestsPage,
  MedicationAdministrationsPage,
  MedicationStatementsPage,
  NutritionOrdersPage,
  ObservationsPage,
  OperationOutcomesPage,
  PlanDefinitionsPage,
  ProceduresPage,
  QuestionnairesPage,
  QuestionnaireResponsesPage,
  ResearchStudiesPage,
  ResearchSubjectsPage,
  ServiceRequestsPage,
  TasksPage,
  ValueSetsPage,
  PractitionersPage,
  ListsPage,
  CommunicationsPage
} from '../ui-pages';

// ConsentsPage is now in ui-pages export
import DiagnosticReportsPage from '../ui-fhir/diagnosticReports/DiagnosticReportsPage';
import DiagnosticReportDetail from '../ui-fhir/diagnosticReports/DiagnosticReportDetail';
import BodyStructuresPage from '../ui-fhir/bodyStructures/BodyStructuresPage';
import BodyStructureDetail from '../ui-fhir/bodyStructures/BodyStructureDetail';
import ClinicalImpressionsPage from '../ui-fhir/clinicalImpressions/ClinicalImpressionsPage';
import ClinicalImpressionDetail from '../ui-fhir/clinicalImpressions/ClinicalImpressionDetail';
import RiskAssessmentsPage from '../ui-fhir/riskAssessments/RiskAssessmentsPage';
import RiskAssessmentDetail from '../ui-fhir/riskAssessments/RiskAssessmentDetail';
import ImagingStudiesPage from '../ui-fhir/imagingStudies/ImagingStudiesPage';
import ImagingStudyDetail from '../ui-fhir/imagingStudies/ImagingStudyDetail';
import AppointmentsPage from '../ui-fhir/appointments/AppointmentsPage';
import AppointmentDetail from '../ui-fhir/appointments/AppointmentDetail';
import SchedulesPage from '../ui-fhir/schedules/SchedulesPage';
import ScheduleDetail from '../ui-fhir/schedules/ScheduleDetail';
import PractitionerRolesPage from '../ui-fhir/practitionerRoles/PractitionerRolesPage';
import PractitionerRoleDetail from '../ui-fhir/practitionerRoles/PractitionerRoleDetail';
import MediasPage from '../ui-fhir/medias/MediasPage';
import MediaDetail from '../ui-fhir/medias/MediaDetail';
import MeasuresPage from '../ui-fhir/measures/MeasuresPage';
import MeasureDetail from '../ui-fhir/measures/MeasureDetail';
import MeasureReportsPage from '../ui-fhir/measureReports/MeasureReportsPage';
import MeasureReportDetail from '../ui-fhir/measureReports/MeasureReportDetail';
import MessageHeadersPage from '../ui-fhir/messageHeaders/MessageHeadersPage';
import MessageHeaderDetail from '../ui-fhir/messageHeaders/MessageHeaderDetail';
import SupplyDeliveriesPage from '../ui-fhir/supplyDeliveries/SupplyDeliveriesPage';
import SupplyRequestsPage from '../ui-fhir/supplyRequests/SupplyRequestsPage';
import EndpointsPage from '../ui-fhir/endpoints/EndpointsPage';
import EndpointDetail from '../ui-fhir/endpoints/EndpointDetail';
import OrganizationsPage from '../ui-fhir/organizations/OrganizationsPage';
import OrganizationDetail from '../ui-fhir/organizations/OrganizationDetail';

import {
  ActivityDefinitionDetail,
  AllergyIntoleranceDetail,
  ArtifactAssessmentDetail,
  BasicDetail,
  BundleDetail,
  CarePlanDetail,
  CareTeamDetail,
  ClaimDetail,
  CodeSystemDetail,
  CommunicationDetail,
  CompositionDetail,
  ConditionDetail,
  ConsentDetail,
  DeviceDetail,
  DocumentReferenceDetail,
  EncounterDetail,
  EvidenceDetail,
  GoalDetail,
  GuidanceResponseDetail,
  ImmunizationDetail,
  LibraryDetail,
  ListDetail,
  LocationDetail,
  MedicationAdministrationDetail,
  MedicationRequestDetail,
  MedicationDetail,
  MedicationStatementDetail,
  NutritionOrderDetail,
  ObservationDetail,
  OperationOutcomeDetail,
  PatientDetail,
  PlanDefinitionDetail,
  PractitionerDetail,
  ProcedureDetail,
  QuestionnaireResponseDetail,
  QuestionnaireDetail,
  ResearchStudyDetail,
  ResearchSubjectDetail,
  ServiceRequestDetail,
  TaskDetail,
  ValueSetDetail
} from '../ui-details';

// ConsentDetail is now in ui-details export
// TODO: Create these detail components
// import MediaDetail from '../ui-fhir/medias/MediaDetail';
import SupplyDeliveryDetail from '../ui-fhir/supplyDeliveries/SupplyDeliveryDetail';
import SupplyRequestDetail from '../ui-fhir/supplyRequests/SupplyRequestDetail';

import NutritionIntakesPage from '../ui-fhir/nutritionIntakes/NutritionIntakesPage';
import NutritionIntakeDetail from '../ui-fhir/nutritionIntakes/NutritionIntakeDetail';

import NutritionProductsPage from '../ui-fhir/nutritionProducts/NutritionProductsPage';
import NutritionProductDetail from '../ui-fhir/nutritionProducts/NutritionProductDetail';

import AuditEventsPage from '../ui-fhir/auditEvents/AuditEventsPage';
import AuditEventDetail from '../ui-fhir/auditEvents/AuditEventDetail';

import SubstancesPage from '../ui-fhir/substances/SubstancesPage';
import SubstanceDetail from '../ui-fhir/substances/SubstanceDetail';


//===============================================================================================================
// PACIO Pages

import MyProfilePage from './pages/MyProfilePage.jsx';
import FhirResourcesDashboard from './FhirResourcesDashboard.jsx';
import FhirResourcesIndex from './FhirResourcesIndex.jsx';

//===============================================================================================================


//===============================================================================================================
// Theming

import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

import { createTheme } from '@mui/material/styles';
import { Tracker } from 'meteor/tracker';


//===============================================================================================================
// FHIR UI Components
// 
// Now using centralized virtual indexes for better organization and cross-resource patterns

import '../ui-tables';  // Auto-registers all Tables on Meteor.Tables

//===============================================================================================================
// Data Cursors

import { ActivityDefinitions } from '../lib/schemas/SimpleSchemas/ActivityDefinitions';
import { AllergyIntolerances } from '../lib/schemas/SimpleSchemas/AllergyIntolerances';
import { ArtifactAssessments } from '../lib/schemas/SimpleSchemas/ArtifactAssessments';
import { AuditEvents } from '../lib/schemas/SimpleSchemas/AuditEvents';
import { BodyStructures } from '../lib/schemas/SimpleSchemas/BodyStructures';
import { Bundles } from '../lib/schemas/SimpleSchemas/Bundles';
import { ClinicalImpressions } from '../lib/schemas/SimpleSchemas/ClinicalImpressions';
import { CarePlans } from '../lib/schemas/SimpleSchemas/CarePlans';
import { CareTeams } from '../lib/schemas/SimpleSchemas/CareTeams';
import { Conditions } from '../lib/schemas/SimpleSchemas/Conditions';
import { Claims } from '../lib/schemas/SimpleSchemas/Claims';
import { CodeSystems } from '../lib/schemas/SimpleSchemas/CodeSystems';
import { Communications } from '../lib/schemas/SimpleSchemas/Communications';
import { CommunicationRequests } from '../lib/schemas/SimpleSchemas/CommunicationRequests';
import { Compositions } from '../lib/schemas/SimpleSchemas/Compositions';
import { ConceptMaps } from '../lib/schemas/SimpleSchemas/ConceptMaps';
import { Devices } from '../lib/schemas/SimpleSchemas/Devices';
import { DiagnosticReports } from '../lib/schemas/SimpleSchemas/DiagnosticReports';
import { DocumentReferences } from '../lib/schemas/SimpleSchemas/DocumentReferences';
import { Encounters } from '../lib/schemas/SimpleSchemas/Encounters';
import { Evidences } from '../lib/schemas/SimpleSchemas/Evidences';
import { Endpoints } from '../lib/schemas/SimpleSchemas/Endpoints';
import { ExplanationOfBenefits } from '../lib/schemas/SimpleSchemas/ExplanationOfBenefits';
import { FamilyMemberHistories } from '../lib/schemas/SimpleSchemas/FamilyMemberHistories';
import { Goals } from '../lib/schemas/SimpleSchemas/Goals';
import { Groups } from '../lib/schemas/SimpleSchemas/Groups';
import { GuidanceResponses } from '../lib/schemas/SimpleSchemas/GuidanceResponses';
import { Immunizations } from '../lib/schemas/SimpleSchemas/Immunizations';
import { ImagingStudies } from '../lib/schemas/SimpleSchemas/ImagingStudies';
import { Libraries } from '../lib/schemas/SimpleSchemas/Libraries';
import { Lists } from '../lib/schemas/SimpleSchemas/Lists';
import { Locations } from '../lib/schemas/SimpleSchemas/Locations';
import { Medications } from '../lib/schemas/SimpleSchemas/Medications';
import { MedicationAdministrations } from '../lib/schemas/SimpleSchemas/MedicationAdministrations';
import { MedicationRequests } from '../lib/schemas/SimpleSchemas/MedicationRequests';
import { MedicationStatements } from '../lib/schemas/SimpleSchemas/MedicationStatements';
import { Measures } from '../lib/schemas/SimpleSchemas/Measures';
import { MeasureReports } from '../lib/schemas/SimpleSchemas/MeasureReports';
import { MessageHeaders } from '../lib/schemas/SimpleSchemas/MessageHeaders';
import { Organizations } from '../lib/schemas/SimpleSchemas/Organizations';
import { Observations } from '../lib/schemas/SimpleSchemas/Observations';
import { OperationOutcomes } from '../lib/schemas/SimpleSchemas/OperationOutcomes';
import { Patients } from '../lib/schemas/SimpleSchemas/Patients';
import { PlanDefinitions } from '../lib/schemas/SimpleSchemas/PlanDefinitions';
import { Practitioners } from '../lib/schemas/SimpleSchemas/Practitioners';
import { Procedures } from '../lib/schemas/SimpleSchemas/Procedures';
import { Questionnaires } from '../lib/schemas/SimpleSchemas/Questionnaires';
import { QuestionnaireResponses } from '../lib/schemas/SimpleSchemas/QuestionnaireResponses';
import { NutritionOrders } from '../lib/schemas/SimpleSchemas/NutritionOrders';
import { ResearchStudies } from '../lib/schemas/SimpleSchemas/ResearchStudies';
import { ResearchSubjects } from '../lib/schemas/SimpleSchemas/ResearchSubjects';
import { ServiceRequests } from '../lib/schemas/SimpleSchemas/ServiceRequests';
import { StructureDefinitions } from '../lib/schemas/SimpleSchemas/StructureDefinitions';
import { Specimens } from '../lib/schemas/SimpleSchemas/Specimens';
import { Tasks } from '../lib/schemas/SimpleSchemas/Tasks';
import { ValueSets } from '../lib/schemas/SimpleSchemas/ValueSets';

import PatientCard from '../patient/PatientCard.jsx'
import { FhirUtilities } from '../lib/FhirUtilities.js'
import { FhirDehydrator } from '../lib/FhirDehydrator.js'
import { DynamicFhirDetail, getDynamicFhirComponent } from '../lib/DynamicFhirDetail.js'
import { DynamicFhirViews, getDynamicFhirViewComponent } from '../lib/DynamicFhirViews.js'
import { LayoutHelpers } from '../lib/LayoutHelpers.js'
import { DynamicSpacer } from './DynamicSpacer'
import MedicalRecordImporter from '../lib/MedicalRecordImporter.js'
import { HipaaLogger } from '../lib/HipaaLogger.js'


Meteor.Collections = {
  ActivityDefinitions,
  AllergyIntolerances,
  ArtifactAssessments,
  AuditEvents,
  Bundles,
  BodyStructures,
  CarePlans,
  CareTeams,
  Claims,
  ClinicalImpressions,
  CodeSystems,
  ConceptMaps,
  Conditions,
  Communications,
  CommunicationRequests,
  Compositions,
  Devices,
  DiagnosticReports,
  DocumentReferences,
  Encounters,
  Evidences,
  Endpoints,
  ExplanationOfBenefits,
  FamilyMemberHistories,
  Goals,
  Groups,
  GuidanceResponses,
  Immunizations,
  Libraries,
  Lists,
  Locations,
  Medications,
  MedicationAdministrations,
  MedicationRequests,
  MedicationStatements,
  MessageHeaders,
  Measures,
  MeasureReports,
  NutritionOrders,
  Organizations,
  Observations,
  OperationOutcomes,
  Patients,
  PlanDefinitions,
  Practitioners,
  Procedures,
  Questionnaires,
  QuestionnaireResponses,
  ResearchStudies,
  ResearchSubjects,
  StructureDefinitions,
  ServiceRequests,
  Specimens,
  Tasks,
  ValueSets
}
Meteor.FhirUtilities = FhirUtilities;
Meteor.FhirDehydrator = FhirDehydrator;
Meteor.LayoutHelpers = LayoutHelpers;
Meteor.DynamicSpacer = DynamicSpacer;
Meteor.NoDataWrapper = NoDataWrapper;
Meteor.NotFoundPage = NotFoundPage;
Meteor.NotSignedInWrapper = NotSignedInWrapper;
Meteor.MedicalRecordImporter = MedicalRecordImporter;
Meteor.PatientCard = PatientCard;
Meteor.NoPatientSelectedCard = NoPatientSelectedCard;
Meteor.HipaaLogger = HipaaLogger;
Meteor.DynamicFhirDetail = DynamicFhirDetail;
Meteor.getDynamicFhirComponent = getDynamicFhirComponent;
Meteor.DynamicFhirViews = DynamicFhirViews;
Meteor.getDynamicFhirViewComponent = getDynamicFhirViewComponent;
Meteor.React = React;



window.Collections = {
  ActivityDefinitions,
  AllergyIntolerances,
  ArtifactAssessments,
  AuditEvents,
  Bundles,
  BodyStructures,
  CarePlans,
  CareTeams,
  Claims,
  CodeSystems,
  ConceptMaps,
  Conditions,
  Communications,
  CommunicationRequests,
  Compositions,
  Devices,
  DiagnosticReports,
  DocumentReferences,
  Encounters,
  Evidences,
  Endpoints,
  FamilyMemberHistories,
  Goals,
  Groups,
  GuidanceResponses,
  Immunizations,
  ImagingStudies,
  Lists,
  Locations,
  Libraries,
  Medications,
  MedicationAdministrations,
  MedicationRequests,
  MedicationStatements,
  MessageHeaders,
  Measures,
  MeasureReports,
  NutritionOrders,
  Organizations,
  Observations,
  OperationOutcomes,
  Patients,
  PlanDefinitions,
  Practitioners,
  Procedures,
  Questionnaires,
  QuestionnaireResponses,
  ResearchStudies,
  ResearchSubjects,
  StructureDefinitions,
  ServiceRequests,
  Specimens,
  Tasks,
  ValueSets,
  FhirDehydrator
}

window.FhirUtilities = FhirUtilities;
window.HipaaLogger = HipaaLogger;

// Make AuditEvents directly accessible in console
window.AuditEvents = AuditEvents;

// SECURITY TODO:  maybe best to put a guard around this 
// debug only?  or maybe only in development mode?
window.Session = Session;

window.React = React;

// Export React Router hooks for packages to use shared Router context
import * as ReactRouterDOM from 'react-router-dom';
window.ReactRouter = ReactRouterDOM;

//===============================================================================================================
// Router History

import { unstable_HistoryRouter as HistoryRouter } from 'react-router-dom';
import { createBrowserHistory } from 'history';
export const history = createBrowserHistory();
import { NavigationProvider, useNavigation } from './NavigationContext';

//===============================================================================================================
// FHIR Module Config Helpers

// Helper to read FHIR module config (supports both boolean and object format)
// Boolean: "AllergyIntolerances": true
// Object:  "Observations": { "enabled": true, "requireAuth": false }
function getFhirModuleConfig(moduleKey) {
  const moduleValue = get(Meteor, 'settings.public.modules.fhir.' + moduleKey);
  const globalRequireAuth = get(Meteor, 'settings.public.modules.fhir.requireAuth', false);

  if (!moduleValue) {
    return { enabled: false, requireAuth: globalRequireAuth };
  }

  if (typeof moduleValue === 'object' && moduleValue !== null) {
    return {
      enabled: get(moduleValue, 'enabled', true),
      requireAuth: 'requireAuth' in moduleValue ? moduleValue.requireAuth : globalRequireAuth
    };
  }

  // moduleValue is truthy (boolean true, or other truthy primitive)
  return { enabled: true, requireAuth: globalRequireAuth };
}

//===============================================================================================================
// Static Routes



let dynamicRoutes = [
  {
    path: "/home",
    element: <HomePage />
  }, {
    path: "/index",
    element: <HomePage />
  }, {
    path: "/getting-started",
    element: <GettingStartedPage />
  }, {
    path: "/getting-started-checklist",
    element: <GettingStartedPage />
  }, {
    path: "/static-files",
    element: <StaticPatientFileLoaderPage />
  }, {
    path: "/smart-launcher",
    element: <SmartLauncher />
  }, {
    path: "/smart-launcher-debugger",
    element: <SmartLaunchDebugger />
  }, {
    path: "/smart-sample-app",
    element: <SmartSampleApp />
  }, {
    path: "/smart-app-debugger",
    element: <SmartAppDebugger />
  }, {
    path: "/backend-auth",
    element: <BackendAuthPage />
  }, {
    path: "/theming",
    element: <ThemingPage />
  }, {
    path: "/cds-hooks-debugger",
    element: <CdsHooksDebugger />
  }, {
    path: "/patient-quickchart",
    element: <PatientQuickChart />
  }, {
    path: "/server-configuration",
    element: <ServerConfigurationPage />
  }, {
    path: "/udap-registration",
    element: <UdapRegistrationPage />
  }, {
    path: "/oauth-clients",
    element: <OAuthClientsPage />
  }, {
    path: "/oauth-patient-picker",
    element: <OAuthPatientPickerPage />
  }, {
    path: "/patient-chart",
    element: <PatientChart />
  }, {
    path: "/biomarkers-charting",
    element: <BiomarkerChartingPage />
  }, {
    path: "/fhir-resources-index",
    element: <FhirResourcesDashboard />,
    requireAuth: true
  }, {
    path: "/fhir-resources-dashboard",
    element: <FhirResourcesIndex />,
    requireAuth: true
  }, {
    path: "/fhir",
    element: <FhirBasePage />
  }, {
    path: "/baseR4",
    element: <FhirBasePage />
  }, {
    path: "/swagger",
    element: <SwaggerPage />
  }
]

// Push FHIR routes with requireAuth from settings
// forceEnabled: for always-on routes (Tasks, Practitioners, etc.) that should be present
//               even when not explicitly configured in settings
function pushFhirRoutes(moduleKey, routes, forceEnabled) {
  const config = getFhirModuleConfig(moduleKey);
  if (!config.enabled && !forceEnabled) return;

  routes.forEach(function(route) {
    dynamicRoutes.push({
      path: route.path,
      element: route.element,
      requireAuth: route.requireAuth !== undefined ? route.requireAuth : config.requireAuth
    });
  });
}

// External Content / iFrame route
if(get(Meteor, 'settings.public.iframe.enabled', false)){
  dynamicRoutes.push({
    path: "/external-content",
    element: <ExternalContentPage />
  });
}

// Business/Legal page routes
if(get(Meteor, 'settings.public.businessPages.privacy.enabled')){
  dynamicRoutes.push({
    path: "/privacy",
    element: <PrivacyPage />
  })
}
if(get(Meteor, 'settings.public.businessPages.terms.enabled')){
  dynamicRoutes.push({
    path: "/terms",
    element: <TermsPage />
  })
  // Also support the legacy route
  dynamicRoutes.push({
    path: "/terms-and-conditions",
    element: <TermsPage />
  })
}
if(get(Meteor, 'settings.public.businessPages.eula.enabled')){
  dynamicRoutes.push({
    path: "/eula",
    element: <EulaPage />
  })
}
if(get(Meteor, 'settings.public.businessPages.support.enabled')){
  dynamicRoutes.push({
    path: "/support",
    element: <SupportPage />
  })
}
if(get(Meteor, 'settings.public.businessPages.about.enabled')){
  dynamicRoutes.push({
    path: "/about",
    element: <AboutPage />
  })
}



// Account routes
if(get(Meteor, 'settings.public.modules.accounts.enabled', true)){
  dynamicRoutes.push({
    path: "/login",
    element: <LoginPage />
  });
  dynamicRoutes.push({
    path: "/signin",
    element: <LoginPage />
  });
  dynamicRoutes.push({
    path: "/sign-in",
    element: <LoginPage />
  });
  dynamicRoutes.push({
    path: "/register", 
    element: <RegisterPage />
  });
  dynamicRoutes.push({
    path: "/signup",
    element: <RegisterPage />
  });
  dynamicRoutes.push({
    path: "/forgot-password",
    element: <ForgotPasswordPage />
  });
  dynamicRoutes.push({
    path: "/verify-email/:token",
    element: <VerifyEmailPage />
  });
  dynamicRoutes.push({
    path: "/reset-password/:token",
    element: <ResetPasswordPage />
  });
  dynamicRoutes.push({
    path: "/enroll-account/:token",
    element: <EnrollAccountPage />
  });
  dynamicRoutes.push({
    path: "/security/two-factor",
    element: <AuthenticatedRoute><TwoFactorSetupPage /></AuthenticatedRoute>
  });
}

if(get(Meteor, 'settings.public.modules.PatientDirectory')){
  dynamicRoutes.push({
    path: "/patient-directory",
    element: <PatientsDirectory />,
    requireAuth: true
  })
}
if(get(Meteor, 'settings.public.modules.Theming')){
  dynamicRoutes.push({
    path: "/theming",
    element: <ThemingPage />
  })
}

// DICOM Viewer routes
if(get(Meteor, 'settings.public.modules.DicomViewer')){
  dynamicRoutes.push({
    path: "/dicom/studies",
    element: <AuthenticatedRoute><StudyListPage /></AuthenticatedRoute>
  })
  dynamicRoutes.push({
    path: "/dicom/upload",
    element: <AuthenticatedRoute><UploadPage /></AuthenticatedRoute>
  })
  // Single file viewing mode (no studyId, uses ?file= query param)
  dynamicRoutes.push({
    path: "/dicom/viewer",
    element: <AuthenticatedRoute><DicomViewerPage /></AuthenticatedRoute>
  })
  // Study viewing mode (with studyId path param)
  dynamicRoutes.push({
    path: "/dicom/viewer/:studyId",
    element: <AuthenticatedRoute><DicomViewerPage /></AuthenticatedRoute>
  })
}

// Optional package routes would be registered here dynamically when packages are added









// FHIR Resource Routes
// Uses pushFhirRoutes() to automatically apply requireAuth from settings.public.modules.fhir
// Supports: global "requireAuth": true on fhir object, or per-resource { "enabled": true, "requireAuth": false }

pushFhirRoutes('ActivityDefinitions', [
  { path: "/activity-definitions", element: <ActivityDefinitionsPage /> },
  { path: "/activity-definitions/new", element: <ActivityDefinitionDetail /> },
  { path: "/activity-definitions/:id", element: <ActivityDefinitionDetail /> }
]);
pushFhirRoutes('AllergyIntolerances', [
  { path: "/allergy-intolerances", element: <AllergyIntolerancesPage /> },
  { path: "/allergy-intolerances/new", element: <AllergyIntoleranceDetail /> },
  { path: "/allergy-intolerances/:id", element: <AllergyIntoleranceDetail /> }
]);
pushFhirRoutes('Appointments', [
  { path: "/appointments", element: <AppointmentsPage /> },
  { path: "/appointments/new", element: <AppointmentDetail /> },
  { path: "/appointments/:id", element: <AppointmentDetail /> }
]);
pushFhirRoutes('ArtifactAssessments', [
  { path: "/artifact-assessments", element: <ArtifactAssessmentsPage /> }
]);
pushFhirRoutes('AuditEvents', [
  { path: "/audit-events", element: <AuditEventsPage /> },
  { path: "/audit-events/new", element: <AuditEventDetail /> },
  { path: "/audit-events/:id", element: <AuditEventDetail /> }
]);
pushFhirRoutes('BodyStructures', [
  { path: "/body-structures", element: <BodyStructuresPage /> },
  { path: "/body-structures/new", element: <BodyStructureDetail /> },
  { path: "/body-structures/:id", element: <BodyStructureDetail /> }
]);
pushFhirRoutes('Bundles', [
  { path: "/bundles", element: <BundlesPage /> }
]);
pushFhirRoutes('CarePlans', [
  { path: "/careplans", element: <CarePlansPage /> },
  { path: "/care-plans", element: <CarePlansPage /> },
  { path: "/careplans/new", element: <CarePlanDetail /> },
  { path: "/careplans/:id", element: <CarePlanDetail /> },
  { path: "/care-plan-designer", element: <EnhancedCarePlanDesigner />, requireAuth: true }
]);
pushFhirRoutes('CareTeams', [
  { path: "/care-teams", element: <CareTeamsPage /> },
  { path: "/care-teams/new", element: <CareTeamDetail /> },
  { path: "/care-teams/:id", element: <CareTeamDetail /> }
]);
pushFhirRoutes('Claims', [
  { path: "/claims", element: <ClaimsPage /> }
]);
pushFhirRoutes('ClinicalImpressions', [
  { path: "/clinical-impressions", element: <ClinicalImpressionsPage /> },
  { path: "/clinical-impressions/new", element: <ClinicalImpressionDetail /> },
  { path: "/clinical-impressions/:id", element: <ClinicalImpressionDetail /> }
]);
pushFhirRoutes('CodeSystems', [
  { path: "/code-systems", element: <CodeSystemsPage /> }
]);
pushFhirRoutes('Compositions', [
  { path: "/compositions", element: <CompositionsPage /> },
  { path: "/compositions/new", element: <CompositionDetail /> },
  { path: "/compositions/:id", element: <CompositionDetail /> }
]);
pushFhirRoutes('Conditions', [
  { path: "/conditions", element: <ConditionsPage /> },
  { path: "/conditions/new", element: <ConditionDetail /> },
  { path: "/conditions/:id", element: <ConditionDetail /> }
]);
pushFhirRoutes('Consents', [
  { path: "/consents", element: <ConsentsPage /> },
  { path: "/consents/new", element: <ConsentDetail /> },
  { path: "/consents/:id", element: <ConsentDetail /> }
]);
pushFhirRoutes('Devices', [
  { path: "/devices", element: <DevicesPage /> },
  { path: "/devices/new", element: <DeviceDetail /> },
  { path: "/devices/:id", element: <DeviceDetail /> }
]);
pushFhirRoutes('DiagnosticReports', [
  { path: "/diagnostic-reports", element: <DiagnosticReportsPage /> },
  { path: "/diagnostic-reports/new", element: <DiagnosticReportDetail /> },
  { path: "/diagnostic-reports/:id", element: <DiagnosticReportDetail /> }
]);
pushFhirRoutes('DocumentReferences', [
  { path: "/document-references", element: <DocumentReferencesPage /> },
  { path: "/document-references/new", element: <DocumentReferenceDetail /> },
  { path: "/document-references/:id", element: <DocumentReferenceDetail /> }
]);
pushFhirRoutes('Encounters', [
  { path: "/encounters", element: <EncountersPage /> },
  { path: "/encounters/new", element: <EncounterDetail /> },
  { path: "/encounters/:id", element: <EncounterDetail /> }
]);
pushFhirRoutes('Endpoints', [
  { path: "/endpoints", element: <EndpointsPage /> },
  { path: "/endpoints/new", element: <EndpointDetail /> },
  { path: "/endpoints/:id", element: <EndpointDetail /> }
]);
pushFhirRoutes('Evidences', [
  { path: "/evidences", element: <EvidencesPage /> }
]);
pushFhirRoutes('Goals', [
  { path: "/goals", element: <GoalsPage /> },
  { path: "/goals/new", element: <GoalDetail /> },
  { path: "/goals/:id", element: <GoalDetail /> }
]);
pushFhirRoutes('GuidanceResponses', [
  { path: "/guidance-responses", element: <GuidanceResponsesPage /> }
]);
pushFhirRoutes('ImagingStudies', [
  { path: "/imaging-studies", element: <ImagingStudiesPage /> },
  { path: "/imaging-studies/new", element: <ImagingStudyDetail /> },
  { path: "/imaging-studies/:id", element: <ImagingStudyDetail /> }
]);
pushFhirRoutes('Immunizations', [
  { path: "/immunizations", element: <ImmunizationsPage /> },
  { path: "/immunizations/new", element: <ImmunizationDetail /> },
  { path: "/immunizations/:id", element: <ImmunizationDetail /> }
]);
pushFhirRoutes('Libraries', [
  { path: "/libraries", element: <LibrariesPage /> }
]);
pushFhirRoutes('Locations', [
  { path: "/locations", element: <LocationsPage /> },
  { path: "/locations/new", element: <LocationDetail /> },
  { path: "/locations/:id", element: <LocationDetail /> }
]);
pushFhirRoutes('Measures', [
  { path: "/measures", element: <MeasuresPage /> },
  { path: "/measures/new", element: <MeasureDetail /> },
  { path: "/measures/:id", element: <MeasureDetail /> }
]);
pushFhirRoutes('MeasureReports', [
  { path: "/measure-reports", element: <MeasureReportsPage /> },
  { path: "/measure-reports/new", element: <MeasureReportDetail /> },
  { path: "/measure-reports/:id", element: <MeasureReportDetail /> }
]);
pushFhirRoutes('Medias', [
  { path: "/medias", element: <MediasPage /> },
  { path: "/medias/new", element: <MediaDetail /> },
  { path: "/medias/:id", element: <MediaDetail /> }
]);
pushFhirRoutes('Medications', [
  { path: "/medications", element: <MedicationsPage /> },
  { path: "/medications/new", element: <MedicationDetail /> },
  { path: "/medications/:id", element: <MedicationDetail /> }
]);
pushFhirRoutes('MedicationAdministrations', [
  { path: "/medication-administrations", element: <MedicationAdministrationsPage /> },
  { path: "/medication-administrations/new", element: <MedicationAdministrationDetail /> },
  { path: "/medication-administrations/:id", element: <MedicationAdministrationDetail /> }
]);
pushFhirRoutes('MedicationRequests', [
  { path: "/medication-requests", element: <MedicationRequestsPage /> },
  { path: "/medication-requests/new", element: <MedicationRequestDetail /> },
  { path: "/medication-requests/:id", element: <MedicationRequestDetail /> }
]);
pushFhirRoutes('MedicationStatements', [
  { path: "/medication-statements", element: <MedicationStatementsPage /> }
]);
pushFhirRoutes('MessageHeaders', [
  { path: "/message-headers", element: <MessageHeadersPage /> },
  { path: "/message-headers/new", element: <MessageHeaderDetail /> },
  { path: "/message-headers/:id", element: <MessageHeaderDetail /> }
]);
pushFhirRoutes('NutritionIntakes', [
  { path: "/nutrition-intakes", element: <NutritionIntakesPage /> },
  { path: "/nutrition-intakes/new", element: <NutritionIntakeDetail /> },
  { path: "/nutrition-intakes/:id", element: <NutritionIntakeDetail /> }
]);
pushFhirRoutes('NutritionOrders', [
  { path: "/nutrition-orders", element: <NutritionOrdersPage /> },
  { path: "/nutrition-orders/new", element: <NutritionOrderDetail /> },
  { path: "/nutrition-orders/:id", element: <NutritionOrderDetail /> }
]);
pushFhirRoutes('NutritionProducts', [
  { path: "/nutrition-products", element: <NutritionProductsPage /> },
  { path: "/nutrition-products/new", element: <NutritionProductDetail /> },
  { path: "/nutrition-products/:id", element: <NutritionProductDetail /> }
]);
pushFhirRoutes('Observations', [
  { path: "/observations", element: <ObservationsPage /> },
  { path: "/observations/new", element: <ObservationDetail /> },
  { path: "/observations/:id", element: <ObservationDetail /> }
]);
pushFhirRoutes('OperationOutcomes', [
  { path: "/operation-outcomes", element: <OperationOutcomesPage /> }
]);
pushFhirRoutes('Organizations', [
  { path: "/organizations", element: <OrganizationsPage /> },
  { path: "/organizations/new", element: <OrganizationDetail /> },
  { path: "/organizations/:id", element: <OrganizationDetail /> }
]);
pushFhirRoutes('Patients', [
  { path: "/patients", element: <PatientsDirectory /> },
  { path: "/patients/new", element: <PatientDetail /> },
  { path: "/patients/:id", element: <PatientDetail /> }
]);
pushFhirRoutes('PlanDefinitions', [
  { path: "/plan-definitions", element: <PlanDefinitionsPage /> },
  { path: "/plan-definitions/new", element: <PlanDefinitionDetail /> },
  { path: "/plan-definitions/:id", element: <PlanDefinitionDetail /> }
]);
pushFhirRoutes('Procedures', [
  { path: "/procedures", element: <ProceduresPage /> },
  { path: "/procedures/new", element: <ProcedureDetail /> },
  { path: "/procedures/:id", element: <ProcedureDetail /> }
]);
pushFhirRoutes('Questionnaires', [
  { path: "/questionnaires", element: <QuestionnairesPage /> },
  { path: "/questionnaires/new", element: <QuestionnaireDetail /> },
  { path: "/questionnaires/:id", element: <QuestionnaireDetail /> }
]);
pushFhirRoutes('QuestionnaireResponses', [
  { path: "/questionnaire-responses", element: <QuestionnaireResponsesPage /> },
  { path: "/questionnaire-responses/new", element: <QuestionnaireResponseDetail /> },
  { path: "/questionnaire-responses/:id", element: <QuestionnaireResponseDetail /> }
]);
pushFhirRoutes('ResearchStudies', [
  { path: "/research-studies", element: <ResearchStudiesPage /> },
  { path: "/research-studies/new", element: <ResearchStudyDetail /> },
  { path: "/research-studies/:id", element: <ResearchStudyDetail /> }
]);
pushFhirRoutes('ResearchSubjects', [
  { path: "/research-subjects", element: <ResearchSubjectsPage /> },
  { path: "/research-subjects/new", element: <ResearchSubjectDetail /> },
  { path: "/research-subjects/:id", element: <ResearchSubjectDetail /> }
]);
pushFhirRoutes('RiskAssessments', [
  { path: "/risk-assessments", element: <RiskAssessmentsPage /> },
  { path: "/risk-assessments/new", element: <RiskAssessmentDetail /> },
  { path: "/risk-assessments/:id", element: <RiskAssessmentDetail /> }
]);
pushFhirRoutes('Schedules', [
  { path: "/schedules", element: <SchedulesPage /> },
  { path: "/schedules/new", element: <ScheduleDetail /> },
  { path: "/schedules/:id", element: <ScheduleDetail /> }
]);
pushFhirRoutes('ServiceRequests', [
  { path: "/service-requests", element: <ServiceRequestsPage /> },
  { path: "/service-requests/new", element: <ServiceRequestDetail /> },
  { path: "/service-requests/:id", element: <ServiceRequestDetail /> }
]);
pushFhirRoutes('Substances', [
  { path: "/substances", element: <SubstancesPage /> },
  { path: "/substances/new", element: <SubstanceDetail /> },
  { path: "/substances/:id", element: <SubstanceDetail /> }
]);
pushFhirRoutes('SupplyDeliveries', [
  { path: "/supply-deliveries", element: <SupplyDeliveriesPage /> },
  { path: "/supply-deliveries/new", element: <SupplyDeliveryDetail /> },
  { path: "/supply-deliveries/:id", element: <SupplyDeliveryDetail /> }
]);
pushFhirRoutes('SupplyRequests', [
  { path: "/supply-requests", element: <SupplyRequestsPage /> },
  { path: "/supply-requests/new", element: <SupplyRequestDetail /> },
  { path: "/supply-requests/:id", element: <SupplyRequestDetail /> }
]);
pushFhirRoutes('ValueSets', [
  { path: "/value-sets", element: <ValueSetsPage /> }
]);

// Always-on routes (present even without explicit settings config)
// These still respect global requireAuth if set
pushFhirRoutes('Tasks', [
  { path: "/tasks", element: <TasksPage /> },
  { path: "/tasks/new", element: <TaskDetail /> },
  { path: "/tasks/:id", element: <TaskDetail /> }
], true);
pushFhirRoutes('Practitioners', [
  { path: "/practitioners", element: <PractitionersPage /> },
  { path: "/practitioners/new", element: <PractitionerDetail /> },
  { path: "/practitioners/:id", element: <PractitionerDetail /> }
], true);
pushFhirRoutes('PractitionerRoles', [
  { path: "/practitioner-roles", element: <PractitionerRolesPage /> },
  { path: "/practitioner-roles/new", element: <PractitionerRoleDetail /> },
  { path: "/practitioner-roles/:id", element: <PractitionerRoleDetail /> }
], true);
pushFhirRoutes('Lists', [
  { path: "/lists", element: <ListsPage /> },
  { path: "/lists/new", element: <ListDetail /> },
  { path: "/lists/:id", element: <ListDetail /> }
], true);
pushFhirRoutes('Communications', [
  { path: "/communications", element: <CommunicationsPage /> },
  { path: "/communications/new", element: <CommunicationDetail /> },
  { path: "/communications/:id", element: <CommunicationDetail /> }
], true);

// PACIO Routes are now handled by the pacio-core package
dynamicRoutes.push({
  path: "/my-profile", 
  element: <MyProfilePage />
});

// ==============================================================================
// Dynamic Routes

let headerNavigation;
let foundMainPage = false;

// ==============================================================================
// WorkflowRegistry Routes (NPM packages)
// NOTE: Workflow routes are now added dynamically by StyledMainRouter using useWorkflowRoutes hook
// This allows routes to be added AFTER async workflow loading completes
// The hook subscribes to WorkflowRegistry changes and re-renders when workflows register

// ==============================================================================
// Atmosphere Package Routes
Object.keys(Package).forEach(function(packageName){
  if(Package[packageName].DynamicRoutes){
    // we try to build up a route from what's specified in the package
    Package[packageName].DynamicRoutes.forEach(function(route){
      // Don't create element here - it will be created in the Routes component
      // Just keep the component reference
      // if(route.component && !route.element) {
      //   route.element = React.createElement(route.component);
      // }

      // Debug logging for swarm route
      if(route.path === '/swarm') {
        console.log('[APP] Swarm route found:', route);
        console.log('[APP] Swarm route element:', route.element);
        console.log('[APP] Swarm route element type:', typeof route.element);
        if(route.element && route.element.$$typeof) {
          console.log('[APP] Swarm element $$typeof:', route.element.$$typeof.toString());
        }
      }

      // Debug logging for routes with requireAuth
      if(route.requireAuth) {
        console.log('[APP] Route requires authentication:', route.path, route);
      }

      dynamicRoutes.push(route);
    });
    if(Package[packageName].MainPage){
      dynamicRoutes.push(Package[packageName].MainPage);
      foundMainPage = true;
    }
  }
});

// ==============================================================================
// Root Route Resolution
// Priority: settings.public.defaults.route > Atmosphere MainPage > GettingStartedPage
//
// This runs AFTER Atmosphere packages are scanned so that all routes
// (including package-provided ones like /pacio-exam-room) are available.

let defaultRoutePath = get(Meteor, 'settings.public.defaults.route', '/');

if (defaultRoutePath && defaultRoutePath !== '/') {
  const matchingRoute = dynamicRoutes.find(route => route.path === defaultRoutePath);
  if (matchingRoute && matchingRoute.element) {
    // Replace or add the "/" route with the settings-specified component
    const rootIndex = dynamicRoutes.findIndex(r => r.path === '/');
    if (rootIndex !== -1) {
      dynamicRoutes[rootIndex] = {
        ...dynamicRoutes[rootIndex],
        element: matchingRoute.element
      };
    } else {
      dynamicRoutes.push({ path: '/', element: matchingRoute.element });
    }
    console.log('[APP] Root route overridden by settings.public.defaults.route:', defaultRoutePath);
  } else {
    console.warn(`[APP] Default route "${defaultRoutePath}" not found in dynamicRoutes. Using existing "/" route.`);
    if (!foundMainPage) {
      dynamicRoutes.push({ path: '/', element: <GettingStartedPage /> });
    }
  }
} else if (!foundMainPage) {
  dynamicRoutes.push({ path: '/', element: <GettingStartedPage /> });
}

// ==============================================================================
// Router
console.log('Total dynamic routes:', dynamicRoutes.length);
console.log('All routes:', dynamicRoutes.map(r => r.path));

const router = createBrowserRouter(dynamicRoutes);

// Router debugging - check for problematic routes
if (Meteor.isDevelopment) {
  dynamicRoutes.forEach((route, index) => {
    if (route.element && typeof route.element === 'object' && route.element.$$typeof) {
      // Check if this might be a problematic element
      if (route.element.$$typeof.toString() !== 'Symbol(react.element)') {
        console.warn(`Route ${index}: path="${route.path}" has unusual element type:`, route.element.$$typeof.toString(), route.element);
      }
    }
  });
}

// ==============================================================================
// Security Based Routing

// patient authentication function
const requireAuth = (nextState, replace) => {
  // do we even need to authorize?
  if(get(Meteor, 'settings.public.defaults.requireAuthorization')){
    // yes, this is a restricted page
    if (!Meteor.loggingIn() && !Meteor.currentUser()) {
      // we're in the compiled desktop app that somebody purchased or downloaded
      // so no need to go to the landing page
      // lets just take them to the signin page
      if(Meteor.isDesktop){
        replace({
          pathname: '/signin',
          state: { nextPathname: nextState.location.pathname }
        });  
      } else {

        // we're in the general use case
        // user is trying to access a route that requires authorization, but isn't signed in
        // redirect them to the landing page
        if(get(Meteor, 'settings.public.defaults.landingPage')){
          replace({
            pathname: get(Meteor, 'settings.public.defaults.landingPage'),
            state: { nextPathname: nextState.location.pathname }
          });    
        } else {
          replace({
            pathname: '/landing-page',
            state: { nextPathname: nextState.location.pathname }
          });    
        }

      }
    }

  } else {
  // apparently we don't need to authorize;
  // so lets just continue (i.e. everybody is authorized)
    if(get(Meteor, 'settings.public.defaults.route')){
      // hey, a default route is specified
      // lets go there
      replace({
        pathname: get(Meteor, 'settings.public.defaults.route'),
        state: { nextPathname: nextState.location.pathname }
      });  
    }

    // can't find anywhere else to go to, so lets just go to the root path 
    // ¯\_(ツ)_/¯
  }
};

// practitioner authentication function
const requirePractitioner = (nextState, replace) => {
  if (!Roles.userIsInRole(get(Meteor.currentUser(), '_id'), 'practitioner')) {
    replace({
      pathname: '/need-to-be-practitioner',
      state: { nextPathname: nextState.location.pathname }
    });
  }
};
// practitioner authentication function
const requreSysadmin = (nextState, replace) => {
  if (!Roles.userIsInRole(get(Meteor.currentUser(), '_id'), 'sysadmin')) {
    replace({
      pathname: '/need-to-be-sysadmin',
      state: { nextPathname: nextState.location.pathname }
    });
  }
};



//===============================================================================================================
// Analytics

let analyticsMeasurementId = get(Meteor, 'settings.public.google.analytics.measurementId')

import ReactGA from "react-ga4";
if(analyticsMeasurementId){
  ReactGA.initialize(analyticsMeasurementId, {debug: get(Meteor, 'settings.public.google.analytics.debug', false)});
}

function logPageView() {
  if(analyticsMeasurementId){
    // ReactGA.pageview(window.location.pathname + window.location.search);
    ReactGA.send({ hitType: "pageview", page: window.location.pathname });
  }
};

function usePageViews() {
  // let location = useLocation();
  React.useEffect(() => {
    if(analyticsMeasurementId){
      ReactGA.pageview(window.location.pathname + window.location.search);
      // ReactGA.set({ page: window.location.pathname });  
      ReactGA.send({ hitType: "pageview", page: window.location.pathname });
    }
  }, [window.location]);
}





// ==============================================================================
// Slideout Cards ???


if(Meteor.isClient){
  Session.setDefault('slideOutCardsVisible', true);
  Session.setDefault('externalContentUrl', get(Meteor, 'settings.public.iframe.url', ''));
  Session.setDefault('secondPanelOpen', false);
}
export function SlideOutCards(props){


  const slideOutCardsVisible = useTracker(function(){
    return Session.get('slideOutCardsVisible')
  }, []);

  console.log('slideOutCardsVisible', slideOutCardsVisible)

  let overlayContainerStyle = {
    position: 'fixed',
    top: '0px',
    left: '0px',
    height: '100%', 
    width: '100%'
  }

  let overlayStyle = {
    position: 'absolute',
    float: 'right',    
    top: '128px',
    right: '73px',
    height: window.innerHeight - 64 + 'px',
    width: '400px',
    transition: '.7s'
  }

  if(slideOutCardsVisible){
    overlayStyle.right = '-473px';
  }


  return <div id='slideoutCardsContainer' style={overlayContainerStyle}>
    <Card id='slideoutCards' style={overlayStyle}>
      <CardHeader title="Slideout" />
    </Card>
  </div>
}



//===============================================================================================================
// Theming


const ThemeContext = createContext();

export const useTheme = () => useContext(ThemeContext);
Meteor.useTheme = useTheme;

// Export React Router hooks via Meteor object for use in packages
Meteor.useLocation = ReactRouterDOM.useLocation;
Meteor.useNavigate = ReactRouterDOM.useNavigate;
Meteor.useParams = ReactRouterDOM.useParams;

// this Provider components enables the useTheme() hook in child components
export const CustomThemeProvider = ({ children }) => {
  const [theme, setTheme] = useState(function() {
    const settingsMode = get(Meteor, 'settings.public.theme.darkMode', false);
    const paletteMode = get(Meteor, 'settings.public.theme.palette.mode', '');
    return settingsMode || paletteMode === 'dark' ? 'dark' : 'light';
  });
  const [themeRefreshCounter, setThemeRefreshCounter] = useState(0);

  // Create themes dynamically based on current Meteor.settings
  const createDynamicTheme = (mode) => {
    const isDark = mode === 'dark';
    
    // Get core color settings - let MUI handle the dark/light variants
    const primaryColor = get(Meteor, "settings.public.theme.palette.primaryColor", "rgb(158, 158, 158)");
    const secondaryColor = get(Meteor, "settings.public.theme.palette.secondaryColor", "#fdb813");
    const errorColor = get(Meteor, "settings.public.theme.palette.errorColor", "rgb(128,20,60)");
    
    // Get AppBar colors with dark mode support
    // Light mode: defaults to primary color if not specified
    const appBarColorLight = get(Meteor, "settings.public.theme.palette.appBarColor", primaryColor);
    const appBarTextColorLight = get(Meteor, "settings.public.theme.palette.appBarTextColor", "#ffffff");
    
    // Dark mode: defaults to light mode values if not specified
    const appBarColorDark = get(Meteor, "settings.public.theme.palette.appBarColorDark", appBarColorLight);
    const appBarTextColorDark = get(Meteor, "settings.public.theme.palette.appBarTextColorDark", appBarTextColorLight);
    
    // Select the appropriate colors based on current mode
    const appBarColor = isDark ? appBarColorDark : appBarColorLight;
    const appBarTextColor = isDark ? appBarTextColorDark : appBarTextColorLight;
    
    // Get background colors with dark mode support
    const backgroundCanvas = get(Meteor, "settings.public.theme.palette.backgroundCanvas", "");
    const backgroundCanvasDark = get(Meteor, "settings.public.theme.palette.backgroundCanvasDark", backgroundCanvas);
    const backgroundPageColorLight = get(Meteor, "settings.public.theme.palette.backgroundPageColor", "");
    const backgroundPageColorDark = get(Meteor, "settings.public.theme.palette.backgroundPageColorDark", backgroundPageColorLight);
    const backgroundPageColor = isDark ? (backgroundCanvasDark || backgroundPageColorDark) : (backgroundCanvas || backgroundPageColorLight);

    // Get card/paper colors from settings with dark mode support
    // When settings are dark-oriented (darkMode: true), the unsuffixed paperColor/cardColor
    // are dark values — don't use them as light-mode values when the user toggles to light mode
    const settingsAreDarkOriented = get(Meteor, 'settings.public.theme.darkMode', false)
      || get(Meteor, 'settings.public.theme.palette.mode', '') === 'dark';

    const paperColorGeneric = get(Meteor, "settings.public.theme.palette.paperColor", "");
    const paperColorDarkExplicit = get(Meteor, "settings.public.theme.palette.paperColorDark", "");
    const paperColorLightExplicit = get(Meteor, "settings.public.theme.palette.paperColorLight", "");

    let paperColorFromSettings;
    if (isDark) {
      paperColorFromSettings = paperColorDarkExplicit || paperColorGeneric;
    } else {
      paperColorFromSettings = paperColorLightExplicit || (settingsAreDarkOriented ? '' : paperColorGeneric);
    }

    const cardColorGeneric = get(Meteor, "settings.public.theme.palette.cardColor", "");
    const cardColorDarkExplicit = get(Meteor, "settings.public.theme.palette.cardColorDark", "");
    const cardColorLightExplicit = get(Meteor, "settings.public.theme.palette.cardColorLight", "");

    let cardColorFromSettings;
    if (isDark) {
      cardColorFromSettings = cardColorDarkExplicit || cardColorGeneric;
    } else {
      cardColorFromSettings = cardColorLightExplicit || (settingsAreDarkOriented ? '' : cardColorGeneric);
    }

    const themeConfig = {
      palette: {
        mode: mode,
        primary: {
          main: primaryColor
        },
        secondary: {
          main: secondaryColor
        },
        error: {
          main: errorColor
        },
        // Custom appbar palette
        appbar: {
          main: appBarColor,
          contrastText: appBarTextColor
        }
      },
      components: {
        MuiAppBar: {
          styleOverrides: {
            root: {
              backgroundColor: appBarColor,
              color: appBarTextColor
            },
            colorPrimary: {
              backgroundColor: appBarColor,
              color: appBarTextColor
            }
          }
        },
        MuiDrawer: {
          styleOverrides: {
            paper: {
              backgroundColor: isDark ? '#1e1e1e' : '#ffffff',
              color: isDark ? 'rgba(255, 255, 255, 0.87)' : 'rgba(0, 0, 0, 0.87)'
            }
          }
        },
        MuiCard: {
          styleOverrides: {
            root: {
              backgroundColor: isDark ? '#1e1e1e' : '#ffffff',
              color: isDark ? 'rgba(255, 255, 255, 0.87)' : 'rgba(0, 0, 0, 0.87)'
            }
          }
        },
        MuiTableHead: {
          styleOverrides: {
            root: {
              backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5'
            }
          }
        },
        MuiTableCell: {
          styleOverrides: {
            head: {
              backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5',
              color: isDark ? 'rgba(255, 255, 255, 0.87)' : 'rgba(0, 0, 0, 0.87)',
              fontWeight: 600
            },
            body: {
              color: isDark ? 'rgba(255, 255, 255, 0.87)' : 'rgba(0, 0, 0, 0.87)'
            }
          }
        },
        MuiTableRow: {
          styleOverrides: {
            head: {
              backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5'
            }
          }
        }
      },
      typography: {
        fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
      }
    };
    
    // Add background colors from settings (handle empty strings)
    const backgroundDefault = backgroundPageColor ? backgroundPageColor : (isDark ? '#121212' : '#fafafa');
    const paperColor = paperColorFromSettings ? paperColorFromSettings.replace(' !important', '').trim() : '';
    const backgroundPaper = paperColor || (isDark ? '#1e1e1e' : '#ffffff');

    themeConfig.palette.background = {
      default: backgroundDefault,
      paper: backgroundPaper
    };
    
    return createTheme(themeConfig);
  };

  // Create theme based on current mode and settings
  const muiTheme = useMemo(() => {
    return createDynamicTheme(theme);
  }, [theme, themeRefreshCounter]);

  const toggleTheme = () => {
    setTheme((prevTheme) => (prevTheme === 'light' ? 'dark' : 'light'));
  };

  // Function to force theme refresh when settings change
  const refreshTheme = () => {
    setThemeRefreshCounter(prev => prev + 1);
  };

  // Listen for theme refresh requests via Session
  useEffect(() => {
    if(Meteor.isClient){
      const handle = Tracker.autorun(() => {
        const refreshRequest = Session.get('themeRefreshRequest');
        if (refreshRequest) {
          refreshTheme();
          Session.set('themeRefreshRequest', false);
        }
      });
      
      return () => handle.stop();
    }
  }, []);

  return (
    <ThemeContext.Provider value={{ theme, setTheme, toggleTheme, refreshTheme }}>
      <ThemeProvider theme={muiTheme}>
        <CssBaseline />
        {children}
      </ThemeProvider>
    </ThemeContext.Provider>
  );
};



if(Meteor.isClient){
  Session.setDefault('canvasBackgroundColor', "#f2f2f2")
}


const drawerWidth =  get(Meteor, 'settings.public.defaults.drawerWidth', 280);
const defaultCanvasColor =  get(Meteor, 'settings.public.theme.palette.canvasColor', "#f2f2f2");

// custom hook to listen to the resize event
function useWindowSize() {
  const [size, setSize] = useState([0, 0]);

  // useLayoutEffect only works on the client!
  if(Meteor.isClient){
    useLayoutEffect(() => {
      function updateSize() {
        setSize([window.innerWidth, window.innerHeight]);
      }
      window.addEventListener('resize', updateSize);
      updateSize();
      return () => window.removeEventListener('resize', updateSize);
    }, []);  
  }
  return size;
}




// ==============================================================================
// Main App


export function App(props){

  // const { theme, toggleTheme } = useTheme();


  
  // if(typeof logger === "undefined"){
  //   logger = props.logger;
  // }
  
  // logger.debug('Rendering the main App.');
  // logger.verbose('client.app.layout.App');
  // logger.data('App.props', {data: props}, {source: "AppContainer.jsx"});

  // console.info('Rendering the App.');
  // console.debug('client.app.layout.App');
  // console.data('App.props', {data: props}, {source: "AppContainer.jsx"});


  // ------------------------------------------------------------------
  // Props  

  const { staticContext, startAdornment,  ...otherProps } = props;

  // ------------------------------------------------------------------
  // SMART on FHIR Oauth Scope  

  let searchParams = new URLSearchParams(window.location.search);
  if(get(Meteor, 'settings.public.enableEhrLaunchContext')){
    if(searchParams){

      searchParams.forEach(function(value, key){
        console.log(key + ': ' + value); 
      });
  
      if(searchParams.get('iss')){
        Session.set('smartOnFhir_iss', searchParams.get('iss'));
      }
      if(searchParams.get('launch')){
        Session.set('smartOnFhir_launch', searchParams.get('launch'));
      }
      if(searchParams.get('code')){
        Session.set('smartOnFhir_code', searchParams.get('code'));
      }
      if(searchParams.get('scope')){
        Session.set('smartOnFhir_scope', searchParams.get('scope'));
      }
  
      if(searchParams.state){
        Session.set('smartOnFhir_state', searchParams.state);
      }        
    }  
  }

  // forgot why we have this.  I think this is Google Analytics related?
  // usePageViews();


  // ------------------------------------------------------------------
  // App UI State

  const [drawerIsOpen, setDrawerIsOpen] = useState(false);
  const [appWidth, appHeight] = useWindowSize();



  // ------------------------------------------------------------------
  // Pathname Updates

  const navigate = useNavigation();
  useEffect(() => {
    // Storing navigate function globally
    window.globalNavigate = navigate;
  }, [navigate]);

  useEffect(() => {
    if(get(props, 'location.pathname')){
      console.info('Location pathname was changed.  Setting the session variable: ' + props.location.pathname);
      Session.set('pathname', props.location.pathname);  
      logPageView()
    }

    if(document.getElementById("reactCanvas") && !Meteor.isCordova){
      document.getElementById("reactCanvas").setAttribute("style", "bottom: 0px; background: " + defaultCanvasColor + ";");
      document.getElementById("reactCanvas").setAttribute("background", defaultCanvasColor);
    }
  }, [props])


  // ------------------------------------------------------------------
  // Dynamic Layout CSS Variables
  // Sets CSS variables for header/footer heights based on visibility state

  const displayNavbars = useTracker(function(){
    return Session.get("displayNavbars");
  }, []);

  const showProminentHeader = useTracker(function(){
    const prominentHeaderSetting = get(Meteor, 'settings.public.defaults.prominentHeader', false);
    const selectedPatient = Session.get("selectedPatient");
    const selectedPatientId = Session.get("selectedPatientId");
    const hasPatient = !!(selectedPatient || selectedPatientId);
    return prominentHeaderSetting && hasPatient;
  }, []);

  // Set CSS variables on document root for dynamic layout calculations
  useLayoutEffect(function(){
    const headerHeight = (displayNavbars !== false) ? (showProminentHeader ? 128 : 64) : 0;
    const footerHeight = (displayNavbars !== false) ? 64 : 0;

    document.documentElement.style.setProperty('--header-height', `${headerHeight}px`);
    document.documentElement.style.setProperty('--footer-height', `${footerHeight}px`);
    document.documentElement.style.setProperty('--total-nav-height', `${headerHeight + footerHeight}px`);
  }, [displayNavbars, showProminentHeader]);


  // ------------------------------------------------------------------
  // Keyboard Shortcut Event Listeners
  // Bridges custom DOM events from hotkeys.js to React state

  useEffect(() => {
    function onToggleDrawer() {
      setDrawerIsOpen(prev => !prev);
    }
    function onToggleFhirModules() {
      const current = get(Meteor, 'settings.public.defaults.sidebar.menuItems.FhirAutoLinks', false);
      set(Meteor, 'settings.public.defaults.sidebar.menuItems.FhirAutoLinks', !current);
      Session.set('settingsRefreshRequest', Date.now());
    }
    function onToggleIndexPage() {
      const current = get(Meteor, 'settings.public.defaults.sidebar.menuItems.IndexPage', false);
      set(Meteor, 'settings.public.defaults.sidebar.menuItems.IndexPage', !current);
      Session.set('settingsRefreshRequest', Date.now());
    }
    function onToggleConstructionZone() {
      const current = get(Meteor, 'settings.public.defaults.sidebar.menuItems.ConstructionZone', false);
      set(Meteor, 'settings.public.defaults.sidebar.menuItems.ConstructionZone', !current);
      Session.set('settingsRefreshRequest', Date.now());
    }
    function onToggleServerConfiguration() {
      const current = get(Meteor, 'settings.public.defaults.sidebar.menuItems.ServerConfiguration', false);
      set(Meteor, 'settings.public.defaults.sidebar.menuItems.ServerConfiguration', !current);
      Session.set('settingsRefreshRequest', Date.now());
    }

    window.addEventListener('toggleDrawer', onToggleDrawer);
    window.addEventListener('toggleFhirModules', onToggleFhirModules);
    window.addEventListener('toggleIndexPage', onToggleIndexPage);
    window.addEventListener('toggleConstructionZone', onToggleConstructionZone);
    window.addEventListener('toggleServerConfiguration', onToggleServerConfiguration);
    return () => {
      window.removeEventListener('toggleDrawer', onToggleDrawer);
      window.removeEventListener('toggleFhirModules', onToggleFhirModules);
      window.removeEventListener('toggleIndexPage', onToggleIndexPage);
      window.removeEventListener('toggleConstructionZone', onToggleConstructionZone);
      window.removeEventListener('toggleServerConfiguration', onToggleServerConfiguration);
    };
  }, []);


  // ------------------------------------------------------------------
  // User Interface Methods

  function handleDrawerOpen(){
    logger.trace('App.handleDrawerOpen()')
    setDrawerIsOpen(!drawerIsOpen);
  };

  function handleDrawerClose(){
    setDrawerIsOpen(false);
    logger.trace('App.handleDrawerClose()')

  };

  const handleDrawerToggle = () => {
    setDrawerIsOpen(!drawerIsOpen);
  };



  // ------------------------------------------------------------------
  // Social Media Registration  

  let socialmedia = {
    title: get(Meteor, 'settings.public.socialmedia.title', ''),
    type: get(Meteor, 'settings.public.socialmedia.type', ''),
    url: get(Meteor, 'settings.public.socialmedia.url', ''),
    image: get(Meteor, 'settings.public.socialmedia.image', ''),
    description: get(Meteor, 'settings.public.socialmedia.description', ''),
    site_name: get(Meteor, 'settings.public.socialmedia.site_name', ''),
    author: get(Meteor, 'settings.public.socialmedia.author', '')
  }

  let helmet;
  let headerTags = [];
  let themeColor = "";  
  let rawColor = get(Meteor, 'settings.public.theme.palette.appBarColor', "#669f64");

  // all we're doing here is grabing the hex color, and ignoring adornments like !important
  if(rawColor.split(" ")){
    themeColor = rawColor.split(" ")[0];
  } else {
    themeColor = rawColor;
  }

  let initialScale = 1.0; 

  headerTags.push(<meta key='theme' name="theme-color" content={themeColor} />)
  headerTags.push(<meta key='utf-8' charSet="utf-8" />);    
  // headerTags.push(<meta name="viewport" key='viewport' property="viewport" content={"initial-scale=" + initialScale + ", minimal-ui, minimum-scale=" + initialScale + ", maximum-scale=" + initialScale + ", width=device-width, height=device-height, user-scalable=no"} />);
  headerTags.push(<meta name="viewport" key='viewport' property="viewport" content={"initial-scale=" + initialScale + ", minimal-ui, minimum-scale=" + initialScale + ", maximum-scale=" + initialScale + ", width=device-width, height=device-height"} />);
  headerTags.push(<meta name="description" key='description' property="description" content={get(Meteor, 'settings.public.title', "Node on FHIR")} />);
  headerTags.push(<title key='title'>{get(Meteor, 'settings.public.title', "Node on FHIR")}</title>);

  if(get(Meteor, 'settings.public.socialmedia')){
    //headerTags.push(<title>{socialmedia.title}</title>);    
    headerTags.push(<link key='canonical' rel="canonical" href={socialmedia.url} />);    
    headerTags.push(<meta prefix="og: http://ogp.me/ns#" key='og:title' property="og:title" content={socialmedia.title} />);
    headerTags.push(<meta prefix="og: http://ogp.me/ns#" key='og:type' property="og:type" content={socialmedia.type} />);
    headerTags.push(<meta prefix="og: http://ogp.me/ns#" key='og:url' property="og:url" content={socialmedia.url} />);
    headerTags.push(<meta prefix="og: http://ogp.me/ns#" key='og:image' property="og:image" content={socialmedia.image} />);
    headerTags.push(<meta prefix="og: http://ogp.me/ns#" key='og:description' property="og:description" content={socialmedia.description} />);
    headerTags.push(<meta prefix="og: http://ogp.me/ns#" key='og:site_name' property="og:site_name" content={socialmedia.site_name} />);
    headerTags.push(<meta prefix="og: http://ogp.me/ns#" key='og:author' property="og:author" content={socialmedia.author} />);
  }

  helmet = <Helmet>
    { headerTags }
  </Helmet>



  // if(theme === "light"){
  //   mainAppStyle.background = backgroundCanvas;
  // } else {
  //   mainAppStyle.background = backgroundCanvasDark;
  // }


  let renderContents = <div { ...otherProps } style={{height: '100vh', display: 'flex', flexDirection: 'column'}}>
    {/* { helmet } */}
    <div id='primaryFlexPanel' style={{height: '100%', display: 'flex', flexDirection: 'column'}}>
      <CustomThemeProvider>
        <Router>
          <NavigationProvider>
            <Header
              drawerIsOpen={drawerIsOpen}
              handleDrawerOpen={handleDrawerOpen}
              headerNavigation={headerNavigation}
              history={window.history}
              { ...otherProps }
            />
            <SideDrawer
              drawerIsOpen={drawerIsOpen}
              onDrawerClose={function(){setDrawerIsOpen(false)}}
              location={props.location}
              history={window.history}
              { ...otherProps } />
            <WelcomeDialog />
            <Box sx={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
              <StyledMainRouter style={{flex: 1}} />
              <SecondaryIframePanel />
            </Box>
            <Footer
              drawerIsOpen={drawerIsOpen}
              location={props.location}
              history={window.history}
              { ...otherProps }
            />
          </NavigationProvider>
        </Router>
      </CustomThemeProvider>      
    </div>
  </div>

  return(renderContents)
};

function StyledMainRouter(props){

  const {children, style, ...otherProps} = props;
  const { theme, toggleTheme } = useTheme();

  // Get workflow routes reactively - will re-render when workflows are registered
  const { workflowRoutes, isLoading } = useWorkflowRoutes();

  // Combine static dynamicRoutes with workflow routes
  const allRoutes = useMemo(() => {
    const routes = [...dynamicRoutes];

    // Add workflow routes if not already present
    workflowRoutes.forEach(route => {
      if (!routes.find(r => r.path === route.path)) {
        routes.push(route);
      }
    });

    return routes;
  }, [workflowRoutes]);

  // Resolve custom 404 page from WorkflowRegistry (if a workflow registered one)
  const workflowNotFoundPage = useMemo(function() {
    return WorkflowRegistry.getNotFoundPage() || null;
  }, [workflowRoutes]);

  // Track if prominent header is shown
  const showProminentHeader = useTracker(function(){
    const prominentHeaderSetting = get(Meteor, 'settings.public.defaults.prominentHeader', false);
    const selectedPatient = Session.get("selectedPatient");
    const selectedPatientId = Session.get("selectedPatientId");
    // Check if we have either a selected patient object or ID
    const hasPatient = !!(selectedPatient || selectedPatientId);
    return prominentHeaderSetting && hasPatient;
  }, []);

  // Track navbar visibility for padding adjustments
  const displayNavbars = useTracker(function(){
    return Session.get("displayNavbars");
  }, []);

  // Use theme-aware default backgrounds instead of white
  const backgroundCanvas = get(Meteor, 'settings.public.theme.palette.backgroundCanvas', "#f6f6f6");
  const backgroundCanvasDark = get(Meteor, 'settings.public.theme.palette.backgroundCanvasDark', "#121212");

  // Compute background based on current theme
  const backgroundStyle = theme === "light" ? backgroundCanvas : backgroundCanvasDark;

  let mainAppStyle = {
    position: 'relative',
    height: '100%',
    overflowY: 'auto',
    overflowX: 'hidden',
    transition: 'padding-top 0.3s ease-in-out',
    background: backgroundStyle, // Set background here so it's part of the object
    ...style // Merge the passed style prop
  }

  // Compensate for header collapsing when navbars are hidden, so content stays in place.
  // Both maxHeight (header) and paddingTop animate with 0.3s ease-in-out, cancelling out.
  if (displayNavbars === false) {
    mainAppStyle.paddingTop = showProminentHeader ? '128px' : '64px';
  } else if (showProminentHeader) {
    mainAppStyle.paddingTop = '64px';
  }

  // Show loading spinner while workflows are loading (only if manifest has entries)
  if (isLoading) {
    return (
      <main id='mainAppRouter' style={{...mainAppStyle, display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
        <CircularProgress />
      </main>
    );
  }

  return (<main id='mainAppRouter' style={mainAppStyle}>
    <Routes>
      {allRoutes.map((route, index) => {
        // Get the element - create from component if needed
        const routeElement = route.element || (route.component ? React.createElement(route.component) : null);

        // Check if route requires authentication
        if (route.requireAuth) {
          return (
            <Route
              key={index}
              path={route.path}
              element={<AuthenticatedRoute>{routeElement}</AuthenticatedRoute>}
            />
          );
        }
        return <Route key={index} path={route.path} element={routeElement} />;
      })}
      {/* Fallback route for 404 Not Found */}
      <Route path="*" element={workflowNotFoundPage || <NotFoundPage />} />
    </Routes>
  </main>)
}


//===============================================================================================================
// Secondary Iframe Panel (2up mode)

function SecondaryIframePanel(){
  const secondPanelOpen = useTracker(function(){
    return Session.get('secondPanelOpen');
  }, []);
  const secondPanelUrl = useTracker(function(){
    return Session.get('externalContentUrl');
  }, []);

  const iframeEnabled = get(Meteor, 'settings.public.iframe.enabled', false);
  const defaultWidth = get(Meteor, 'settings.public.iframe.defaultWidth', '50%');
  const showAddressBar = get(Meteor, 'settings.public.iframe.showAddressBar', true);

  if(!iframeEnabled || !secondPanelOpen || !secondPanelUrl){
    return null;
  }

  return (
    <Box sx={{
      width: { xs: '100%', md: defaultWidth },
      position: { xs: 'absolute', md: 'relative' },
      right: 0,
      top: 0,
      bottom: 0,
      zIndex: { xs: 1200, md: 'auto' },
      borderLeft: { xs: 0, md: 1 },
      borderColor: 'divider',
      display: 'flex',
      flexDirection: 'column',
      overflow: 'hidden',
      backgroundColor: 'background.paper'
    }}>
      <ExternalContentPanel
        url={secondPanelUrl}
        showAddressBar={showAddressBar}
        onClose={function(){
          Session.set('secondPanelOpen', false);
        }}
        height="100%"
      />
    </Box>
  );
}