// /packages/synthea/client/generatePropertiesFile.js

// Template for generating a synthea.properties file with user configuration
export function generatePropertiesFile(config) {
  // Start with header
  let properties = `# synthea.properties
# Generated by Honeycomb Synthea Configuration Tool
# Generated on: ${new Date().toISOString()}
#
# This file can be used with Synthea by placing it in the appropriate directory
# or by using the --config_file parameter when running Synthea
#

# Exporter Settings
exporter.baseDirectory = ${config.outputDirectory}
exporter.use_uuid_filenames = ${config.useUUIDFilenames}
exporter.subfolders_by_id_substring = false
exporter.pretty_print = ${config.prettyPrint}
exporter.years_of_history = ${config.yearsOfHistory}
exporter.split_records = ${config.splitRecords}
exporter.split_records.duplicate_data = false
exporter.metadata.export = ${config.metadataExport}

# Export Format Settings
exporter.ccda.export = ${config.exportCCDA}
exporter.fhir.export = ${config.exportFormat === 'fhir' ? 'true' : 'false'}
exporter.fhir_stu3.export = false
exporter.fhir_dstu2.export = false
exporter.fhir.use_shr_extensions = false
exporter.fhir.use_us_core_ig = true
exporter.fhir.us_core_version = ${config.usCoreVersion}
exporter.fhir.transaction_bundle = true
# Bulk data format exports as NDJSON files instead of bundles
exporter.fhir.bulk_data = ${config.fhirExportMode === 'bulk' ? 'true' : 'false'}
exporter.hospital.fhir.export = ${config.exportHospitalFHIR}
exporter.practitioner.fhir.export = ${config.exportPractitionerFHIR}
exporter.encoding = UTF-8
exporter.json.export = ${config.exportJSON}
exporter.json.include_module_history = false
exporter.csv.export = ${config.exportCSV}
exporter.csv.append_mode = ${config.csvAppendMode}
exporter.csv.folder_per_run = ${config.csvFolderPerRun}
exporter.text.export = ${config.exportText}
exporter.text.per_encounter_export = false
exporter.clinical_note.export = ${config.exportClinicalNote}

# Symptoms Export
exporter.symptoms.csv.export = ${config.exportSymptoms}
exporter.symptoms.mode = 0
exporter.symptoms.csv.append_mode = false
exporter.symptoms.csv.folder_per_run = false
exporter.symptoms.text.export = false

# Generation Settings
# Default population is specified via command line -p parameter
generate.default_population = ${config.populationSize}
generate.thread_pool_size = ${config.threadPoolSize}
generate.only_dead_patients = ${config.onlyDeadPatients}
generate.only_alive_patients = ${config.onlyAlivePatients}
generate.max_attempts_to_keep_patient = ${config.maxAttemptsToKeepPatient}
generate.track_detailed_transition_metrics = ${config.trackDetailedTransitions}

# Demographics Settings
generate.append_numbers_to_person_names = ${config.appendNumbersToNames}
generate.middle_names = ${config.includeMiddleNames ? (config.middleNameProbability / 100).toFixed(2) : '0'}
generate.veteran_population_override = ${config.veteranPopulationOverride}

# Socioeconomic Weights
generate.demographics.socioeconomic.weights.income = ${(config.socioeconomicWeightIncome / 100).toFixed(2)}
generate.demographics.socioeconomic.weights.education = ${(config.socioeconomicWeightEducation / 100).toFixed(2)}
generate.demographics.socioeconomic.weights.occupation = ${(config.socioeconomicWeightOccupation / 100).toFixed(2)}

# Provider Settings
generate.providers.selection_behavior = ${config.providerSelection}
generate.providers.maximum_search_distance = ${config.maxSearchDistance}
generate.providers.default_to_hospital_on_failure = ${config.defaultToHospitalOnFailure}
generate.providers.minimum = ${config.minimumProviders}

# Insurance Settings
generate.insurance.mandate.year = ${config.insuranceMandateYear}
generate.insurance.employer_coverage = ${(config.employerCoverage / 100).toFixed(2)}

# Payer Settings
generate.payers.selection_behavior = ${config.payerSelectionBehavior}
generate.payers.insurance_plans.income_premium_ratio = ${(config.incomeBasedPremiumRatio / 100).toFixed(3)}

# Cost Calculation
generate.costs.method = ${config.costMethod}
generate.costs.default_procedure_cost = ${config.defaultProcedureCost.toFixed(2)}
generate.costs.default_medication_cost = ${config.defaultMedicationCost.toFixed(2)}
generate.costs.default_encounter_cost = ${config.defaultEncounterCost.toFixed(2)}
generate.costs.default_immunization_cost = ${config.defaultImmunizationCost.toFixed(2)}
generate.costs.default_lab_cost = ${config.defaultLabCost.toFixed(2)}
# Device and supply costs are typically included in procedure costs
generate.costs.default_device_cost = 0.00
generate.costs.default_supply_cost = 0.00

# Lifecycle Settings
lifecycle.death_by_natural_causes = ${config.deathByNaturalCauses}
lifecycle.death_by_loss_of_care = ${config.deathByLossOfCare}

# Logging Settings
generate.log_patients.detail = ${config.logPatientDetail}
# options are "none", "simple", or "detailed"

# Clinical Settings
# Set the number of clinicians in the simulation
generate.clinician_pool_size = ${config.clinicianPoolSize}

# Additional Settings can be added below
# See https://github.com/synthetichealth/synthea/wiki/Basic-Setup-and-Running
# for more configuration options
`;

  return properties;
}