// npmPackages/data-importer/lib/GenomicsFileClassifier.js
//
// Recognizes genomics files dropped on /import-data (23andMe raw txt, FASTQ,
// VCF, BAM) so they can be routed to the genome-central workflow instead of
// falling through the generic text/binary paths.
//
// Dependency-free CommonJS (BundleReferenceResolver precedent): the CI
// lib-unit-tests job runs `node --test` off a bare checkout with no npm
// install, and this package has no "type": "module" so plain node classifies
// .js as CJS. ESM import sites (FileDropTab) interop fine.

'use strict';

// Extensions that are genomics files by name alone. '.txt' is only a
// CANDIDATE — the caller must sniff its content with sniff23andMeText before
// claiming it (most .txt drops are not genotype exports).
var GENOMICS_EXTENSIONS = [
  '.fq', '.fastq', '.fq.gz', '.fastq.gz', '.vcf', '.vcf.gz', '.bam'
];

/**
 * Quick routing check: could this file be a genomics import?
 * @param {File|{name: string}} file
 * @returns {boolean}
 */
function isGenomicsCandidateFile(file) {
  if (!file || !file.name) return false;
  var name = file.name.toLowerCase();
  for (var i = 0; i < GENOMICS_EXTENSIONS.length; i++) {
    if (name.endsWith(GENOMICS_EXTENSIONS[i])) return true;
  }
  return name.endsWith('.txt');
}

/**
 * Content sniff for 23andMe raw genotype exports (mirrors
 * genome-central's lib/parse23andMe.js sniff23andMeHeader — keep in sync).
 * @param {string} firstChunk - first ~2KB of the file's text
 * @returns {boolean}
 */
function sniff23andMeText(firstChunk) {
  if (typeof firstChunk !== 'string' || firstChunk.length === 0) {
    return false;
  }
  if (/generated by 23andMe/i.test(firstChunk)) {
    return true;
  }
  return /rsid\s+chromosome\s+position\s+genotype/i.test(firstChunk);
}

/**
 * Classify candidate files into genomics types.
 *
 * Classification rules:
 *   .txt + positive sniff       → type: 'genomics-snp',   label: '23andMe Raw Genotypes'
 *   .fq/.fastq(.gz)             → type: 'genomics-fastq', label: 'Sequencing Reads (FASTQ)'
 *   .vcf(.gz)                   → type: 'genomics-vcf',   label: 'Variant Calls (VCF)'
 *   .bam                        → type: 'genomics-bam',   label: 'Aligned Reads (BAM)'
 *   .txt + negative/no sniff    → (not classified)
 *
 * @param {Array} fileArray - File objects (or {name} stubs in tests)
 * @param {Object} [txtSniffResults] - map of file.name -> boolean sniff outcome
 * @returns {Array} [{ file, type, label, icon }]
 */
function classifyGenomicsFiles(fileArray, txtSniffResults) {
  var sniffMap = txtSniffResults || {};
  var results = [];

  for (var i = 0; i < (fileArray || []).length; i++) {
    var file = fileArray[i];
    if (!file || !file.name) continue;
    var name = file.name.toLowerCase();
    var entry = null;

    if (name.endsWith('.fq') || name.endsWith('.fastq') ||
        name.endsWith('.fq.gz') || name.endsWith('.fastq.gz')) {
      entry = { file: file, type: 'genomics-fastq', label: 'Sequencing Reads (FASTQ)', icon: 'Biotech' };
    } else if (name.endsWith('.vcf') || name.endsWith('.vcf.gz')) {
      entry = { file: file, type: 'genomics-vcf', label: 'Variant Calls (VCF)', icon: 'Biotech' };
    } else if (name.endsWith('.bam')) {
      entry = { file: file, type: 'genomics-bam', label: 'Aligned Reads (BAM)', icon: 'Biotech' };
    } else if (name.endsWith('.txt') && sniffMap[file.name] === true) {
      entry = { file: file, type: 'genomics-snp', label: '23andMe Raw Genotypes', icon: 'Biotech' };
    }

    if (entry) {
      results.push(entry);
    }
  }

  return results;
}

module.exports = {
  GENOMICS_EXTENSIONS: GENOMICS_EXTENSIONS,
  isGenomicsCandidateFile: isGenomicsCandidateFile,
  sniff23andMeText: sniff23andMeText,
  classifyGenomicsFiles: classifyGenomicsFiles
};
