// tests/unit/npmPackages/data-importer/GenomicsFileClassifier.test.mjs
//
// Pure unit tests for genomics file recognition on /import-data.
// Run: npm run test:genomics-classifier  (node --test, no npm deps)

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  isGenomicsCandidateFile,
  sniff23andMeText,
  classifyGenomicsFiles
} from '../../../../npmPackages/data-importer/lib/GenomicsFileClassifier.js';

test('isGenomicsCandidateFile matches genomics extensions and .txt candidates', function() {
  assert.equal(isGenomicsCandidateFile({ name: 'sample.1.fq' }), true);
  assert.equal(isGenomicsCandidateFile({ name: 'sample.1.fq.gz' }), true);
  assert.equal(isGenomicsCandidateFile({ name: 'reads.FASTQ' }), true);
  assert.equal(isGenomicsCandidateFile({ name: 'variants.vcf.gz' }), true);
  assert.equal(isGenomicsCandidateFile({ name: 'aligned.bam' }), true);
  assert.equal(isGenomicsCandidateFile({ name: 'genome_export.txt' }), true, '.txt is a sniff candidate');
  assert.equal(isGenomicsCandidateFile({ name: 'bundle.json' }), false);
  assert.equal(isGenomicsCandidateFile({ name: 'export.zip' }), false);
  assert.equal(isGenomicsCandidateFile(null), false);
});

test('sniff23andMeText recognizes the 23andMe header forms', function() {
  assert.equal(sniff23andMeText('# This data file generated by 23andMe at: ...'), true);
  assert.equal(sniff23andMeText('# rsid\tchromosome\tposition\tgenotype\n'), true);
  assert.equal(sniff23andMeText('{"resourceType":"Bundle"}'), false);
  assert.equal(sniff23andMeText(''), false);
  assert.equal(sniff23andMeText(null), false);
});

test('classifyGenomicsFiles routes by extension and sniff outcome', function() {
  const files = [
    { name: 'reads.1.fq.gz' },
    { name: 'variants.vcf' },
    { name: 'aligned.bam' },
    { name: 'genome_raw.txt' },
    { name: 'notes.txt' },
    { name: 'bundle.json' }
  ];
  const sniffMap = { 'genome_raw.txt': true, 'notes.txt': false };
  const classified = classifyGenomicsFiles(files, sniffMap);

  const byName = {};
  classified.forEach(function(entry) { byName[entry.file.name] = entry; });

  assert.equal(classified.length, 4);
  assert.equal(byName['reads.1.fq.gz'].type, 'genomics-fastq');
  assert.equal(byName['variants.vcf'].type, 'genomics-vcf');
  assert.equal(byName['aligned.bam'].type, 'genomics-bam');
  assert.equal(byName['genome_raw.txt'].type, 'genomics-snp');
  assert.equal(byName['notes.txt'], undefined, 'unsniffed txt stays in the normal pipeline');
  assert.equal(byName['bundle.json'], undefined);
});

test('classifyGenomicsFiles tolerates missing sniff map and empty input', function() {
  assert.deepEqual(classifyGenomicsFiles([], {}), []);
  assert.deepEqual(classifyGenomicsFiles(null), []);
  const classified = classifyGenomicsFiles([{ name: 'genome_raw.txt' }]);
  assert.equal(classified.length, 0, 'txt without a positive sniff is never claimed');
});
